language: php

sudo: false

php:
  - 5.6

# Cache the composer directories
cache:
  directories:
    - $HOME/.composer/cache

# Environment Variables to set
env:
  global:
    - APP_ENV=travis
    # Contains a $GITHUB_TOKEN env var for use with composer to avoid API limits.
    - secure: "AOQgqN74SYafoB+S9DbBx164YVqyJF6qHKbLs+aGWL53FmDy0Umi0Fq+KFAcs4ItzfOxiuQC/vfuYwhFK
havP06pHb9gP2XGVFTDpxF0Fwk+ce8pUHSlAXz/MQIV8F9RMycT8RHiE7exJ31ivP3RkKY1aTnzLUCzvc8S7KGCftlp6
LZx66D1oyl6YTq6ZdbyYwsfcrwYzAjqWMymoXA1eSnM9yecD2pF9xriTslmJaf70wKJrnAfIg7PFEy0kpQvCeTZqY0GE
bFxbhkdkH2DDQxyG01hg83mmBYhgMU2WYnwRCqql7vgJFIDSBwGqs7NmvVboWufQDHqH7Gj/Mb/MRRvqPBeSD2tAfgr5
heSnp8BAzy0+XjBijBkb6COSvkuDXvLMQVeT4Ciqrh+KSRqSZEjPGuXVv9dO4HAMkVX+aAo5xOE/L0nmaTGeRH15Hp90
71teBl1hBwxWWXE8/3BmS/4rmRA/dJ03rWq5QuDCbdW02jK+mysIDhebMuhAfoEwTCCTmtW5+A5itIjSoSb9NSch/ECM
eNa5gEaHjEdkOsTyy39icwUBCBAgJmNBqKrjQXoS1gnyk072UmJXyonXJoFsMlHgZZPi1IZ3RA7yvAlVVgirGqYBky56
qION1b6V9sKa737a3jgz1x/qqBUg9oHC6/3jWUWhIAdkvlLoOw="

# Services to Enable
services:

# Branches to be built or not
branches:
  # Blacklist these branches
  except:
    - staging
    - gh-pages

before_install:
  - composer self-update

install:
  - composer config -g github-oauth.github.com $GITHUB_TOKEN
  - composer install --no-interaction

before_script:
  - phpenv rehash
  - vendor/bin/phpcs --config-set installed_paths vendor/loadsys/loadsys_codesniffer,vendor/cakephp/cakephp-codesniffer

script:
  - vendor/bin/phpcs -p --extensions=php --standard=Loadsys ./src ./tests ./config
  - vendor/bin/phpunit -v --coverage-clover=build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v

notifications:
  email: false
